import tests from "../test.js";
import fs from "fs";

let content = tests.tests.map(category => {
	return [
		`## Examples of ${ category.name.toLowerCase() }\n`,
		...category.tests.map(test => {
			return [
				"### " + test.name,
				test.description || "",
				"```js",
				test.arg,
				"```",
				"becomes:",
				"```js",
				test.expect,
				"```"
			].join("\n\n");
		})
	].join("\n");
});



let readme = fs.readFileSync("README.src.md", "utf8");

readme = "<!-- ⚠️ Do NOT edit this README! It is automatically generated by _build/update-readme.js. Edit README.src.md instead! -->\n" + readme;
readme = readme.replace("<!-- examples -->", content.join("\n\n"));

fs.writeFileSync("README.md", readme);
