import tests from "../test.js";
import fs from "fs";

const TEMPLATE_CATEGORY = (title, examples) =>
`## ${ title }

${ examples.join("\n") }`;

const TEMPLATE_EXAMPLE = (title, description, input, output) =>
`### ${ title }${ description ? "\n" + description : "" }

\`\`\`js
${ input }
\`\`\`

becomes:

\`\`\`js
${ output }
\`\`\`
`;

let content = tests.tests.flatMap(category => {
	let examples = category.tests.map(test => TEMPLATE_EXAMPLE(
		test.name,
		test.description,
		test.arg,
		test.expect,
	));

	return TEMPLATE_CATEGORY(category.name, examples);
});

let readme = fs.readFileSync("README.src.md", "utf8");

readme = "<!-- ⚠️ Do NOT edit this README! It is automatically generated by _build/update-readme.js. Edit README.src.md instead! -->\n" + readme;
readme = readme.replace("<!-- examples -->", content.join("\n\n"));

fs.writeFileSync("README.md", readme);
